### ISSUE TITLE
Project budget

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#10]
## Description

The overall financial cost or amount is a summary total financial sum for the activity.

This is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the default aid type code is administrative costs (G01).

## Proposed tests

Firstly:
```python
Budget available forward annually
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2 or 3
    And `default-aid-type/@code` is not G01
    And `activity-date[@type="3" or @type="4" or @type="end-planned" or @type="end-actual"]/@iso-date` is at least 6 months ahead
    Then `budget | planned-disbursement` should be available forward annually
 ```
 
Secondly:
```python
Budget available forward quarterly
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2 or 3
    And `default-aid-type/@code` is not G01
    And `activity-date[@type="3" or @type="4" or @type="end-planned" or @type="end-actual"]/@iso-date` is at least 6 months ahead
    Then `budget | planned-disbursement` should be available forward quarterly
 ```

**Comment by Melina-Loewer** [comment]
**On behalf of BMZ we would like to raise:** Do both annual and quarterly future values need to be named under the budget values data field in order to receive the full number of points?

Generally: How and when will answers to those questions be communicated?

**Comment by jzheng-79** [comment]
Suggest to drop quarterly data requirement as budget planning for most organizations is probably on an annual basis.

**Comment by publishwhatyoufund** [comment]
**@Melina-Loewer, @jzheng-79**: More points are scored for quarterly budgets since this provides more detailed information about forward looking spending plans. 

If only publishing annual budgets only half of the points will be scored for the indicator. Publishing quarterly budgets passes both the annual and quarterly budget tests.
