### ISSUE TITLE
Project budget document

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#11]
## Description

This is a specific budget detailing what the intended spending is for the different lines of the individual activity.

This can be either at the activity or transaction level, and is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the aid type is budget support (A01 or A02) or if the default aid type code is administrative costs (G01).

## Proposed test

```python
Budget document is present
    Given an IATI activity
     And the activity is current
     And `activity-status/@code` is one of 2, 3 or 4
     And `default-aid-type/@code` is not any of A01, A02 or G01
     And `transaction/aid-type/@code` is not any of A01 or A02
     Then `document-link/category[@code="A05"]` should be present
```

**Comment by AndieVaughn** [comment]
Recommend excluding aid types A and B.

**Comment by ForeignCommonwealthDevelopmentOffice** [comment]
FCDO agrees with Andie

**Comment by jzheng-79** [comment]
UNICEF agrees with comments on excluding aid types A and B.

**Comment by publishwhatyoufund** [comment]
**@AndieVaughn, @ForeignCommonwealthDevelopmentOffice, @jzheng-79**: Budget support aid types A01 and A02 are already excluded from this test. We have done some surveying of data and found that some donors are including budget documents with their core contributions (B aid types).

Since it is possible and more transparent to publish budgets for these activities we will not exclude these aid types.
