### ISSUE TITLE
Commitments

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#12]
## Description

The overall financial cost or amount is a summary total financial sum committed for the activity.

This is only expected if the activity is in the implementation, completion or post-completion phase.

## Proposed test

```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    Then `transaction[transaction-type/@code="2" or transaction-type/@code="C"]` should be present
```

**Comment by jzheng-79** [comment]
Please clarify if zero value is accepted by the test.

**Comment by publishwhatyoufund** [comment]
**@ jzheng-79:** A ‘0’ commitment is not really possible, a commitment would need to have some value otherwise it wouldn’t be a commitment.
