### ISSUE TITLE
Disbursements and expenditures

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#13]
## Description

Individual actual financial disbursements and expenditures must be related to individual activities and must be on a per-transaction basis.

This is only expected if the activity is in the implementation, completion or post-completion phase.

## Proposed test

```python
   Given an IATI activity 
   And the activity is current 
   And `activity-status/@code` is one of 2, 3 or 4 
   Then `transaction[transaction-type/@code="3" or transaction-type/@code="D" or transaction-type/@code="4" or transaction-type/@code="E"]` should be present
```

**Comment by breidertmt** [comment]
In some cases there might be an obligation/commitment, however there might not be a disbursement in the time period reviewed by PWYF for an activity. How will this be taken into account, given you cannot score/report on something that does not exist yet.

**Comment by SidaErik** [comment]
We see the same problem as @breidertmt . Activities can be active without disbursements. This criteria would make more sense if it included transaction type 2.

**Comment by cmmarschner** [comment]
This frequently occurs for MCC. We have activities as part of an overall program that may not begin work, and thus disbursements, sometimes for years (road construction is a good example). This is a case where the "0" value is actually useful information - we have not (and in the case of the budget indicator), do not even intend, to disburse funds in a specific time period.

**Comment by jzheng-79** [comment]
Similar to other's comments, there could be active (current) activities without any disbursement. Would then a "0" value be allowed for the test? Please clarify.

**Comment by publishwhatyoufund** [comment]
**@breidertmt, @cmmarschner, @jzheng-79**: We allow a 0 disbursement or expenditure for this test. The logical approach in this case will be to use a regular expenditure reported amount of "0" rather than adding a zero value disbursement.

**@Erik-Sida**: There is a separate indicator for transaction type 2 (Commitments)
