### ISSUE TITLE
Budget alignment

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#14]
## Description

The budget alignment indicator helps to link the activity to the recipient country government’s own budget codes.

This is only expected if the activity is in the implementation, completion or post-completion phase, and if the aid type is not budget support. This is not expected if the aid type is budget support (A01 or A02) or if the default aid type code is administrative costs (G01).

The test follows the guidance on country budget alignment, found here on the IATI reference website: http://reference.iatistandard.org/203/activity-standard/overview/country-budget-alignment/

This guidance also includes the relevant CRS codelist guidance that will be used for this test.

## Proposed test

Firstly:
```python
   Capital spend is present
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02 or G01
    And `transaction/aid-type/@code` is not any of A01 or A02
    Then `capital-spend` should be present
```

Secondly:
```python
   Publish detailed CRS purpose codes in the sector field
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02 or G01
    And `transaction/aid-type/@code` is not any of A01 or A02
    Then `sector code` should be present
    And `sector code` should not be broad “multisector aid” or “sector not specified” purpose codes
    And `sector code` should be the more detailed “voluntary” CRS purpose codes, not “parent” codes
```

## Proposed change

This indicator was called "Capital spend" in the 2018 Index, and only tested whether the capital spend element was present in an activity.  The proposed change is to add the additional sector code tests that check whether sector codes being used will allow for alignment with country budgets.  This follows IATI guidance on the topic.

This is actually similar to the way the indicator worked in the 2016 Index when it was called "Budget identifier". However, the Budget Identifier codelist was deprecated which is why it was changed to "Capital spend" in 2018. The new budget alignment codelist will be based on the IATI guidance.

**Comment by SidaErik** [comment]
The indicator "Capital spend" should possibly be limited to only default-aid-type/@code C01 and B03. At least B01, B02, category D and category H should also be excluded just as A01, A02 and G01.

**Comment by publishwhatyoufund** [comment]
**@Erik-Sida:** Since we are not sure what the status of capital expenditure is for these aid types we will not exclude them from the test. In cases where no capital expenditure is recorded, these can report 0 capital spend.
