### ISSUE TITLE
Sectors

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#22]
## Description

The sectors of the activity explain whether this is, for example, a health or education project.

## Proposed test
Firstly:
```python
For each current activity,
`sector` should be present
or `transaction/sector` should be present
```
Secondly:
```python
For each current activity,
at least one
`sector[not(@vocabulary)]/@code or sector[@vocabulary="1"]/@code` or `transaction/sector[@vocabulary="1"]/@code` or `transaction/sector[not(@vocabulary)]/@code` should be on the Sector codelist
```

**Comment by publishwhatyoufund** [comment]
We are considering a change to the weighting of the Sector indicator from 3.5 to 3.

**Comment by stevieflow** [comment]
> We are considering a change to the weighting of the Unique ID indicator from 3.5 to 3.

This was not flagged in the "tracked changes" Methodology document, published by PWYF

![2022-Index-Technical-Paper_track-changes-pdf (3)](https://user-images.githubusercontent.com/1209944/134365689-9c45ad1b-265e-4bc3-aed2-e57d238093ce.png)

Given that these proposals are also not in the latest Methodology document, it makes it difficult to understand the impact of this, and other, proposed changes to weightings.  It would be very helpful if PWYF could published a proposed weightings table, to accommodate this

**Comment by stevieflow** [comment]
> We are considering a change to the weighting of the Unique ID indicator from 3.5 to 3.

Note - is this a mistake @publishwhatyoufund ?  The comment mentions Unique ID, but this issue is about Sectors.  Please clarify

**Comment by aschirokauer** [comment]
What value does this information add relative to the Purpose/Voluntary Codes of the OECD?

**Comment by jzheng-79** [comment]
Please clarify the rationale for decreasing weight for this indicator. As this is not included in the 2022 ATI methodology paper, please update the full weight table in order to better understand the impact of all the weight changes.

**Comment by publishwhatyoufund** [comment]
**@stevieflow @jzheng-79**: yes, we will publish a revised weightings table. The weighting for Sectors will decrease from 3.5 to 2.5 points to allow for the increase in the weight of the Descriptions indicator. Apologies for any confusion about this. We feel that this is acceptable also since sector codes are assessed as part of the Budget Alignment indicator. And yes, sorry, this was for the Sectors indicator, the Unique ID indicator will also be reduced from 3.5 to 2.5 points for the same reason. 

**@aschirokauer**: This indicator scores organisation for including a valid sector/purpose code. The Budget Identifier indicator awards additional points for use of specific purpose codes rather than general codes.
