### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#24]
## Description
The activity identifier is a unique reference ID for the activity, e.g. a project number.

## Proposed test

Firstly:
```python
For each current activity, `iati-identifier` should be present
``` 
Secondly:
```python
For each current activity,
either:
`iati-identifier/text()`
should start w​ith `reporting-org/@ref`
o​r
`iati-identifier/text()`
should start w​ith `other-identifier[@type="B1"]/@ref`
```
## Example
If the reporting-org is 44000 then the following example would pass the test:
`<iati-identifier>44000-P126875</iati-identifier>`

While this example would not pass the test:
`<iati-identifier>P126875</iati-identifier>`

**Comment by publishwhatyoufund** [comment]
We are considering a change to the weighting of the Unique ID indicator from 3.5 to 3.

**Comment by stevieflow** [comment]
> We are considering a change to the weighting of the Unique ID indicator from 3.5 to 3.

This was not flagged in the "tracked changes" version of the Methodology document previously released by PWYF.
  
![2022-Index-Technical-Paper_track-changes-pdf (1)](https://user-images.githubusercontent.com/1209944/134364510-d4dfd893-f550-4032-beac-8c52ebcfd4c9.png)

Nor is this in the latest Methodology document

It would be helpful to access a list of proposed weightings, given these new revisions

**Comment by Mhirji** [comment]
I am trying to understand what a unique identifier for a given activity has to do with the transparency of an organization.  This seems to be more around the quality of data than an index trying to measure transparency.

**Comment by jzheng-79** [comment]
Please clarify the rationale for decreasing weight for this indicator. As this is not included in the 2022 ATI methodology paper, please update the full weight table in order to better understand the impact of all the weight changes.

**Comment by publishwhatyoufund** [comment]
**@stevieflow, @jzheng-79**: we are decreasing the weight of this indicator to allow for the increase in the weighting of the Descriptions indicator.

**@Mhirji:** The Unique ID allows users to search for activities across different datasets and portals where project data is available. An important element of transparency is the accessibility and usability of data and this element makes the data easier to access and use.

**Comment by publishwhatyoufund** [comment]
The weighting for Unieq ID will decrease from 3.5 to 2.5 points to allow for the increase in the weight of the Descriptions indicator.
