### ISSUE TITLE
Networked data

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#25]
## Description

The Networked data indicator assesses how organisations provide information about other organisations participating in their activities. It is a two part test. Part 1 is the test previously used for the Implementer indicator:

## Proposed test
```python
Given an IATI activity
     And the activity is current
     And `activity-status/@code` is one of 2, 3 or 4
     Then `participating-org[@role="Implementing" or @role="4"]/@ref | participating-org[@role="Implementing" or @role="4"]/narrative/text()` should have at least 1 character.
```

Part 2 of the indicator assesses use of standardised references for participating organisations in activities. 

We look for references to organisations other than self-references to the publisher themselves. We look for these in their current activities, across the participating organisation roles (Funding, Accountable, Extending and Implementing)

We construct a list of organisation references that will pass the test. These consist of:
·        IATI organisation identifiers from the IATI publishers list
·        OECD DAC CRS Channel Codes that use the prefix ‘XM-DAC’, except for generic or non-specific organisation references 
         (such as “Developing country-based NGO” or “Multilateral Organisations”)
·        Organisation references that are constructed using a valid prefix from the list of [recognised prefixes.
](https://codelists.codeforiati.org/OrganisationRegistrationAgency/)
Each activity receives a percentage score calculated by taking the proportion of participating organisations that have valid references and the total number of participating organisations involved in the activity, i.e.:
These scores will then be averaged across an organisation’s activities to calculate the final score for this test.

**Comment by breidertmt** [comment]
How will PWYF plan to take into account projects which have been redacted due to sensitivities for the health and safety of implementing partners or national security risks/interests, especially in light of the current situation in Afghanistan. The U.S. has standard redaction language which is used and allowable by law and it is in line with OECD/DAC decisions and to protect the security of our implementing partners, programs, and beneficiaries. The U.S. and other donors redact titles, descriptions, and implementing partner names (with the exception of PIOs) for Afghanistan and other sensitive areas e.g. Burma.  We are working internally with USG guidance and externally both with IATI and through our DAC delegate to establish guidance and best practices on how to move forward to balance transparency and sensitive data.

**Comment by stevieflow** [comment]
**1. Ongoing updates of the IATI publishers list**

A practical observation: organisations become new publishers most days/weeks - meaning that the IATI organisation identifiers from the IATI publishers list increase.  Will @publishwhatyoufund therefore align with this list on the exact same date of the final data pull, to ensure that all possible publishers could be cited ?  

**2. Government ministries / departments**

There are legitimate cases where participating-orgs could be government ministries / departments.  It is often the case that these will not be represented on _any_ list, not just the three sources cited by @publishwhatyoufund.  Publishers who declare such detail will fail this test, but have little opportunity to rectify this.  

(_Perhaps_ use of the aidtype field might help filter out such activities?)

**3. Entities in jurisdictions not covered by the prefixes**

The https://codelists.codeforiati.org/OrganisationRegistrationAgency/ list is not complete.  It is unlikely this will ever be complete!  Hence, a use case exists where a publisher can make best efforts to reference an organisation, yet fail this test , given that the prefix chosen is not on the list.  

To note: These observations represent specific challenges for @publishwhatyoufund - but should not detract from the positive direction of travel to make inroads into this important topic

I

**Comment by AndieVaughn** [comment]
Please consider excluding partner names that have been redacted for security purposes from the analysis.  USAID supports the spirit of this indicator and includes these data in IATI when available.  However, there are an increasing number of countries where the release of partner names - especially local partners - may put partners, programs, or beneficiaries at risk and, therefore, releasing detail about the partner is redacted for security purposes.  Please consider this rationale in the analysis.

**Comment by aschirokauer** [comment]
Consider not using a standardized list of implementers to check against. Especially in the event that an organization starts publishing this field to IATI based on this new requirement, your standard list will not contain a large number of those names.

**Comment by Melina-Loewer** [comment]
**On behalf of BMZ we would like to raise:** Do we understand it correctly that the Organisation name (in the IATI data field Org Role 1,2,3,4 **@narrative**) for Part 1 can be used instead of a IATI Org ID (in the data field Org Role 1, 2, 3, 4 **@ref**) to get full points?

**Comment by ForeignCommonwealthDevelopmentOffice** [comment]
Welcome networked indicator approach, but also agree with Stevie on elements relating to eg. other donor governments, and with Andie re. instances eg. in Afghanistan, and other countries where safety of partners means we cannot publish the name.

**Comment by PierreRichardGavi** [comment]
**On behalf of Gavi:** "Gavi also welcome this indicator, and will work to identify partners where possible and feasible.  However, a great number of partners are government ministries, where no such list of identifiers will be practically available.  We welcome some reflection on this reality."

**Comment by cmmarschner** [comment]
Agree with Steven, FCDO and Gavi re: partner country governments. All of MCC's funds are granted directly to governments and there is no accepted way to refer to them.

**Comment by jzheng-79** [comment]
UNICEF welcomes the 'Networked Data' approach. However, we do share similar concerns as the issues mentioned above: 
- Organization reference list is unlikely to be complete, and it requires constant updating. Unless there is a pre-set date for the 'final' reference list, the assessment of this indicator would be inaccurate & unfair.
- For security reason, many partner names cannot be released. Please consider this rationale in the assessment.
- A great number of partners can be government ministries, where publishers will fail the test according to current test. This needs to be taken into consideration for a fair assessment.

Suggest to drop references as a "must" as the partner may not be an IATI publisher, and use narrative (names of organizations and/or types of organizations)

**Comment by publishwhatyoufund** [comment]
**@breidertmt, @AndieVaughn, @ForeignCommonwealthDevelopmentOffice**: publishers will not be penalised for security-related redactions in our IATI data quality sampling, and redacted documents or redaction text will be picked up and scored by our automated tests.

To pass the automated test, a redacted organisation reference would need to follow a standard format included in the list of known IATI organisation prefixes: https://codelists.codeforiati.org/OrganisationRegistrationAgency/ 

**@stevieflow**: thank you for the suggestion, we will make sure we align with the list just before the final data pull. Of course, once a new publisher registers, it may take time before other publishers update their data with their new organisation reference, but we will make sure we align the list when we do the data pull in case there are examples of publishers updating their data straight away or in coordination.

On excluding government ministries, we will exclude aid types A01 and A02 from the test while no recognised references exist for partner country government ministries. This is subject to change if references for these are introduced in the future (for subsequent editions of the Aid Transparency Index).

For jurisdictions where no prefix currently exists, we would encourage publishers work with IATI to add a relevant prefix to the list.

**@aschirokauer**: we are using a list of recognised prefixes. This means all references using a recognised prefix are included. We will also carry out IATI sampling on these references to check that the correct references are being used for each organisation. 

**@Melina-Loewer**: to score points for part 2 of the test a corresponding organisation reference will need to be included for each participating organisation in an activity.

**@PierreRichardGavi, @cmmarschner:** since no recognised references currently exist for most partner country government entities, organsiations that work solely with partner country governments will be excluded from the organisation reference part of the test.

**@jzheng-79**: see answers to most of your questions above. The test has two parts, the first part is for narrative names of implementer organisations, and the second part is for organisation references.

**Comment by publishwhatyoufund** [comment]
This test will be modified to exclude partner country government ministries by excluding aid types A01 and A02 while no recognised references exist for partner country government ministries.
