### ISSUE TITLE
Tied Aid Status

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#29]
## Description

The tied aid status shows whether the organisation states that this activity counts as “tied” (procurement is restricted to the donor organisation country) or “untied” (open procurement).

This can be either at the activity or transaction level, and is only expected if the activity is in the implementation, completion or post-completion phase.

## Proposed test
Firstly:
```python
For each current activity,
if `activity-status/@code` is one of (2, 3, 4)
then `default-tied-status` should be present
or `transaction/tied-status` should be present
```
Secondly:
```python
For each current activity,
if `activity-status/@code` is one of (2, 3, 4)
then at least one `default-tied-status/@code` should be on the TiedStatus codelist
or at least one `transaction/tied-status/@code` should be on the TiedStatus codelist
```

**Comment by SidaErik** [comment]
For this test we would propose excluding tying status for aid types B02, G01 and H02-H05 in line with OECD/DAC CRS reporting instructions.

**Comment by publishwhatyoufund** [comment]
**@Erik-Sida**: since these aid types could include tying of aid we will not exclude them at this time.
