### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#30]
## Description
The terms and conditions of the activity may also be referred to as benchmarks, priors, deliverables or involve words such as “subject to…”. They are specific to an individual activity and explain what the recipient must do in order to be eligible for the funds to be released.
Any policy conditions related to an activity must be published here. 

This is only expected if the activity is in the implementation, completion or post-completion phase.

## Proposed test
Firstly:
```python
For each current activity,
if `activity-status/@code` is one of (2, 3, 4)
And `default-aid-type/@code` is not any of B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
    And `transaction/aid-type/@code` is not any of B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
then `conditions` should be present

```
Secondly:
```python
if `activity-status/@code` is one of (2, 3, 4)
And `default-aid-type/@code` is not any of B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
    And `transaction/aid-type/@code` is not any of B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
then `document-link/category[@code="A04"]` should be present

```

**Comment by publishwhatyoufund** [comment]
We are considering a change to the weighting of the Conditions indicator from 3.5 to 3.

**Comment by breidertmt** [comment]
These conditions should be outlined in any procurement documents as well which is indicator #15 Procurement. What is the intended difference?

**Comment by stevieflow** [comment]
> We are considering a change to the weighting of the Conditions indicator from 3.5 to 3.

This change was not detailed in the "tracked changes" Methodology document

![2022-Index-Technical-Paper_track-changes-pdf (1)](https://user-images.githubusercontent.com/1209944/134365001-54069579-5eed-4f2e-8fa2-854a9aca7ead.png)


It would be helpful to see the context of the revised set of weightings, to understand where things may change

**Comment by AndieVaughn** [comment]
USAID and many other organizations do not have activity-specific conditions. In the case of USAID, any deliverables that must be fulfilled by the implementing partner would be stated in a contract or cooperative agreement - which we find duplicative of the procurement indicator. USAID does have standards that implementing partners must meet, but these are not activity specific and apply across any partner regardless of the activity. These Agency-wide conditions have not been accepted in the previous ATIs, but we'd support the inclusion of organization-wide conditions over leaving the field blank.

**Comment by Melina-Loewer** [comment]
**On behalf of BMZ we would like to raise:** Could you please upload examples for Condition-documents?

The technical paper says: “The IATI Reference for this indicator are conditions and/or conditions document.”
Will the test of the ATI Tracker thus be “firstly” OR “secondly”?

**Comment by ForeignCommonwealthDevelopmentOffice** [comment]
Please be clear on the definition here.   Conditions seems to mix up deliverables, results, conditions of release of funds, which may be contained in different FCDO documents (eg. logframe and agreement with partner, and in the business case in the first place) .

**Comment by jzheng-79** [comment]
Please clarify the rationale for decreasing weight for this indicator. As this is not included in the 2022 ATI methodology paper, please update the full weight table in order to better understand the impact of all the weight changes.

Also similar to USAID and many other organizations, UNICEF does not have 'activity' specific conditions. We sign a Programme Cooperation Agreement (PCA) with our civil society implementing partners, and it governs the CSO’s implementation of any programme activities agreed to with UNICEF in support of the achievement of the Country Programme Document. It outlines general responsibilities of the parties, as well as reporting requirements.

**Comment by publishwhatyoufund** [comment]
**@breidertmt, @AndieVaughn**: Country level conditions can be included alongside project specific conditions. These should be reported at the activity level, however. If the conditions are contained in a contract, the contract should be tagged with both the A04 and A11 codes. 

**@stevieflow:** We will not be changing the weighting of this indicator.

**@Melina-Loewer**: we will be happy to share some examples with you. Activity conditions published as a document or as data in the IATI conditions element are sufficient to pass the test.

**@ForeignCommonwealthDevelopmentOffice, @ jzheng-79**: The definition of conditions from the Index Technical Paper is: “the terms and conditions of the activity may also be referred to as benchmarks, priors, deliverables, or involve words such as “subject to...”. They are specific to an individual activity and explain what the recipient must do in order to be eligible for the funds to be released.
Any policy conditionality related to the activity should be published here.  In cases where there are both terms and conditions and policy conditionalities for an activity, all of these should be declared.”

If conditions are contained in multiple documents these should all be tagged with the A04 conditions document code.
