### ISSUE TITLE
Disaggregated Budget 

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#9]
## Description

Disaggregated budgets are scored for each of the three years ahead for which they are available.

## Approach

We determine the list of recipient countries where we would expect a country budget from the recipient countries of the donor’s current activities. For each of these recipient countries, we then look for annual forward ‘recipient-country-budgets’ for three years forward. Points are awarded for the proportion of recipient countries that have a forward country budget, split evenly for each of the three forward years.

## Example

If a donor has current activities in Senegal and Liberia, we expect forward budgets in both countries for the next three years. If there are forward budget for both countries for two years and a forward budget for Senegal for the third year, the score would be (1/3 * 2/2) + (1/3 * 2/2) + (1/3 * 1/2)

**Comment by ToonVB** [comment]
As is probably also the case for other donors, are institutional set-up & processes does not include countr-envelopes/budgets.
We will calculate & use the sum of expected disbursements & expenditures by country reg. activities we finance, however that does not add any information, since these activities are published as well....

**Comment by Mhirji** [comment]
Should this not take into account when activities are planned to end.  If all activities in Senegal are scheduled to end in 2 years, how would a this actually be calculated?  I would assume that a organization would not be penalized for not having 3 years forward looking budgets for Senegal.

**Comment by randymatthews** [comment]
How can this indicator take into account the situation where budget is planned on an emergency basis, and provided only one year in advance?  Due to that limitation, forward budgets are not available 2 and 3 years ahead and this indicator can be a bit misleading for that situation.

**Comment by jzheng-79** [comment]
UNICEF publishes the board approved budget for the duration of country programme cycle based on Country Programme Document (CPD, publicly available). Each CP generally runs for five years, and the approval of the new CP is typically in the last year of the CP cycle. So it does not seem to be rationale to force a three-year forward-looking period.

**Comment by publishwhatyoufund** [comment]
**@ToonVB**: The disaggregated budget indicator is tested against budgets published in IATI organisation files. These can be either country or thematic based. 

**@Mhirji**: Unfortunately we don’t have a way that the test can pick up program closures like this. However, if publishing full three year budgets for the rest of your country programs this would have a marginal impact on your overall score for the indicator.

**@randymatthews, @jzheng-79**: There are cases where it won’t be possible to publish full three year budgets, estimates will suffice in these cases.
